<template>
  <ClientOnly>
    <Vue3Lottie
      animation-link="https://assets2.lottiefiles.com/packages/lf20_GbabwrUY2k.json"
      :height="200"
      :width="200"
    />
  </ClientOnly>
</template>
