<template>
  <ClientOnly>
    <Vue3Lottie
      animation-link="https://assets7.lottiefiles.com/packages/lf20_Yc2PU8DdfX.json"
      :height="300"
      :width="300"
    />
  </ClientOnly>
</template>
