<template>
  <ClientOnly>
    <Vue3Lottie
      animation-link="https://assets10.lottiefiles.com/packages/lf20_K0864uP6eC.json"
      :height="200"
      :width="200"
      direction="alternate"
    />
  </ClientOnly>
</template>
